node {
    stage('Preparation') { 
        git branch: 'main', url: 'https://github.com/CloudTechDevOps/Terraform-0730am.git'
    }
    stage('Init') {
       dir('Day-1-Terraform-basic-config') {
                  sh  'terraform init'
       }
    }
    stage('Plan') {
        dir('Day-1-Terraform-basic-config') {
                  sh  'terraform plan'
        }
    }
    stage('apply/destroy') {
        dir('Day-1-Terraform-basic-config') {
                  sh  'terraform ${action} -auto-approve'
        }
    }
}
